language: r
sudo: required
dist: trusty
bioc_required: true
cache: packages
install:
 - R -e 'install.packages("remotes")'
 - R -e 'remotes::install_deps(dependencies = T, upgrade = T)'
 - R -e 'remotes::install_local(".")'
